### ISSUE TITLE
could not access file "$libdir/timescaledb-1.4.0": No such file or directory

### ISSUE THREAD

**Issue by waterdrop01** [timescale/timescaledb#1425]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version: postgres (PostgreSQL) 11.5
 - TimescaleDB version: 1.4.1 
 - Installation method: Docker

**Describe the bug**
Postgresql showing the error message ```could not access file "$libdir/timescaledb-1.4.0": No such file or directory``` on any psql command like `SELECT *`.

I did run:
```
docker exec -it timescaledb psql -U postgres -X

# within the PostgreSQL instance
ALTER EXTENSION timescaledb UPDATE;
```
It says the extension is up to date...I don't understand what's going on. 

From inside docker image, here is the output of:
```
bash-5.0# pg_config --pkglibdir
/usr/local/lib/postgresql

bash-5.0# ls /usr/local/lib/postgresql
_int.so                   latin_and_mic.so          timescaledb-tsl-1.3.0.so
adminpack.so              libpqwalreceiver.so       timescaledb-tsl-1.3.1.so
amcheck.so                lo.so                     timescaledb-tsl-1.3.2.so
ascii_and_mic.so          ltree.so                  timescaledb-tsl-1.4.0.so
auth_delay.so             moddatetime.so            timescaledb-tsl-1.4.1.so
auto_explain.so           pageinspect.so            timescaledb.so
autoinc.so                passwordcheck.so          timetravel.so
bloom.so                  pg_buffercache.so         tsm_system_rows.so
btree_gin.so              pg_freespacemap.so        tsm_system_time.so
btree_gist.so             pg_prewarm.so             unaccent.so
citext.so                 pg_stat_statements.so     utf8_and_ascii.so
cube.so                   pg_trgm.so                utf8_and_big5.so
cyrillic_and_mic.so       pg_visibility.so          utf8_and_cyrillic.so
dblink.so                 pgcrypto.so               utf8_and_euc2004.so
dict_int.so               pgoutput.so               utf8_and_euc_cn.so
dict_snowball.so          pgrowlocks.so             utf8_and_euc_jp.so
dict_xsyn.so              pgstattuple.so            utf8_and_euc_kr.so
earthdistance.so          pgxml.so                  utf8_and_euc_tw.so
euc2004_sjis2004.so       pgxs                      utf8_and_gb18030.so
euc_cn_and_mic.so         plpgsql.so                utf8_and_gbk.so
euc_jp_and_sjis.so        postgres_fdw.so           utf8_and_iso8859.so
euc_kr_and_mic.so         refint.so                 utf8_and_iso8859_1.so
euc_tw_and_big5.so        seg.so                    utf8_and_johab.so
file_fdw.so               sslinfo.so                utf8_and_sjis.so
fuzzystrmatch.so          tablefunc.so              utf8_and_sjis2004.so
hstore.so                 tcn.so                    utf8_and_uhc.so
insert_username.so        test_decoding.so          utf8_and_win.so
isn.so                    timescaledb-1.4.1.so      uuid-ossp.so
latin2_and_win1250.so     timescaledb-tsl-1.2.2.so
```

Thanks for your help!

**Comment by RobAtticus** [comment]
Weird, is the output of `\dx` giving you 1.4.1 or 1.4.0?

**Comment by RobAtticus** [comment]
It appears our docker image may be missing some of the libs you need, rebuilding and pushing.

**Comment by RobAtticus** [comment]
Okay @waterdrop01 , if you pull the new alpine images it should work now. It should have the missing `.so`s

**Comment by waterdrop01** [comment]
Thanks @RobAtticus , pulling newest docker image fixed the issue

**Comment by gp-hardik** [comment]
Hi @RobAtticus I am facing the same issue while updating from 1.1.0 . The pg_config --pkglibdir 
doesn't show 1.1.0.so file and the  ERROR:  could not access file "$libdir/timescaledb-1.1.0": No such file or directory ; is still pertaining.  I have tried pulling the latest docker image using timescale/timescaledb:latest-pg10 but still no luck.

**Comment by skrenes** [comment]
I had the same issue when I upgraded my `timescale/timescaledb:latest-pg11` container, which I believe is v1.5.1. The exact error message I was receiving was: `ERROR: could not access file "$libdir/timescaledb-1.3.1": No such file or directory`

I explicitly set the image to `timescale/timescaledb:1.5.0-pg11` and it worked just fine. Can we reopen this issue or is it better to create a new one and perhaps reference this one?

**Comment by RobAtticus** [comment]
@skrenes I will double check the image to make sure it has some older versions, but in the interest of keeping our images small, we like to restrict it to the last ~5 TimescaleDB versions or so. So if you were coming from 1.3.1, that's probably why 1.5.0 worked (has 1.4.2, 1.4.1, 1.4.0, 1.3.2, and 1.3.1) and 1.5.1 did not (has 1.5.0 down to 1.3.2).

**Comment by RobAtticus** [comment]
Which also means you should be able to upgrade to 1.5.1 now that you've gone to 1.5.0

**Comment by RobAtticus** [comment]
I just checked and it looks like that was the issue. the 1.5.1 image has back to 1.3.2 :) So now you should be able to update

**Comment by skrenes** [comment]
Thanks for your rapid response @RobAtticus 
I just tried upgrading again and got the same error. I went back to 1.5.0. and did a maintenance routine on both my databases (vacuum full, reindex, etc) and then tried 1.5.1. again and still got the same error. Any ideas?

I'm not sure why it references 1.3.1 in the error. I've regularly stayed up to date, and as I've said, I was on 1.5.0 before the upgrade.

**Comment by skrenes** [comment]
Oh, I was not aware of the instructions for [upgrading docker containers](https://docs.timescale.com/latest/using-timescaledb/update-db#update-docker-5). After running `ALTER EXTENSION timescaledb UPDATE;` I was able to use the latest container without problems. Thank you for your help! Any chance the container can do this itself upon detecting an older extension?

**Comment by RobAtticus** [comment]
@skrenes Ah yes, you need to run `ALTER EXTENSION`. We can definitely look into auto-altering.

**Comment by tmtron** [comment]
I also just hit this issue - in my case, I have updated our database (called daqmon) - but still got this error. It turned out, that we also had to run `ALTER EXTENSION` in the postgres database.

**Comment by anka** [comment]
@RobAtticus I am facing the same issue after upgrading from 1.4.0 to 1.7.1. It tells me `ERROR:  could not access file "$libdir/timescaledb-1.4.0": No such file or directory`. I did run the `ALTER` statement but this did not fix the problem.

**Comment by RobAtticus** [comment]
@anka For size considerations, we do not include every older version in the Docker image. You will have to do a transitional upgrade. So if you try upgrading to 1.5.0 or 1.6.0 first, it should work.

**Comment by tmtron** [comment]
@RobAtticus do we really need transitional upgrades?  
The [upgrade docs]( https://docs.timescale.com/latest/using-timescaledb/update-db) say:
>`ALTER EXTENSION timescaledb UPDATE;`
>This will upgrade TimescaleDB to the latest installed version, even if you are several versions behind.

So these docs are wrong/outdated?

Just today I've updated an docker installation from 1.4 to 1.7.  
When I connected with `psql -X`
* `\dx` reported this `No such file or director` error
* but after `ALTER EXTENSION timescaledb UPDATE;` it worked an reported the new version. 

Did I miss something?  
Or maybe it just worked, because this instance had no hypertables, yet?

**Comment by RobAtticus** [comment]
@tmtron Yes because the docker images do not contain all previous libraries. Perhaps the docs could be a bit more specific, but it does usually contain at least the previous 5 versions.

**Comment by RobAtticus** [comment]
@tmtron In your case it sounds like it worked though. If `\dx` shows the correct version, then you are good to go.

**Comment by tmtron** [comment]
@RobAtticus thanks for the fast reply - just one clarification please:

>it does usually contain at least the previous 5 versions.

does it count all versions - also patch-level?

e.g. 1.4.2, 1.5.0, 1.5.1, 1.6.0, 1.7.0
* = 5 versions (because 1.5.0 and 1.5.1 are different)
* or only 4 (because 1.5.0 and 1.5.1 are the same)

**Comment by RobAtticus** [comment]
Yes, patch level are their own version.

So 1.7.1 contains:
- 1.7.0
- 1.6.1
- 1.6.0
- 1.5.1
- 1.5.0

**Comment by tmtron** [comment]
@RobAtticus thanks for the info!
seems I was right on time to upgrade my 1.4.2. version :)

**Comment by anka** [comment]
So I did update from `1.4.0` to `1.6.0` to `1.7.2` and now I get the following error within the log files. However, the database starts correctly.

```
2020-07-29 19:29:29.387 UTC [164] LOG:  TimescaleDB background worker launcher connected to shared catalogs
2020-07-29 19:29:29.405 UTC [166] ERROR:  could not access file "$libdir/timescaledb-1.4.0": No such file or directory
2020-07-29 19:29:29.407 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 166) exited with exit code 1
```

However `\dx timescaledb` shows `1.7.2` and everything seems to work correctly. Is there anything more I can check if something is missing?

**Comment by RobAtticus** [comment]
@anka You might have other databases that you need to run `ALTER EXTENSION` in? It has to be run in each database where Timescale is installed, not just one

**Comment by anka** [comment]
@RobAtticus actually not, there is only one database. It looks like the upgrade by using `ALTER EXTENSION` did work but the error is still visible in the log files when restarting postgres.

**Comment by tmtron** [comment]
@anka in psql use `\l` to see all databases.  
We usually have one database with a custom name and sometimes forget to update the (unused) `postgres` database.  
I think once, I even had to update `template0`

**Comment by drm** [comment]
FWIW: For me, an `ALTER UPDATE timescaledb UPDATE` was sufficient to fix a similar issue.

**Comment by PavlovicAndrej** [comment]
IF `UPDATE` doesn't work for you, I have to do this after every brew update of PostgreSQL. I always do just this and it works:

1. start CLI with `psql -d <DB_name>`
2. do this ```DROP EXTENSION IF EXISTS timescaledb CASCADE; CREATE EXTENSION IF NOT EXISTS timescaledb; \dx```

You should se output similar to this one be good to go:
```
                                                List of installed extensions
    Name     | Version |   Schema   |                                      Description
-------------+---------+------------+---------------------------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.17.1  | public     | Enables scalable inserts and complex queries for time-series data (Community Edition)
(2 rows)
```
