### ISSUE TITLE
CentOS/RHEL 8 repo far behind CentOS 7

### ISSUE THREAD

**Issue by msaladna** [timescale/timescaledb#1882]
**Relevant system information:**
 - OS: CentOS 8.1
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.2
 - Installation method: yum/dnf

**Describe the bug**
Best available version on `timescale_timescaledb` repo is 1.4.2 configured via [boilerplate](https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum). No TimescaleDB build exists yet for PostgreSQL 12 either.

**To Reproduce**
```
dnf install -y timescaledb-postgresql-11
rpm -qi timescaledb-postgresql-11
```

or just `dnf  repository-packages timescale_timescaledb list --all`

**Expected behavior**
```
Available Packages
timescaledb-postgresql-10.x86_64     1.7.0-0.el8     timescale_timescaledb 
timescaledb-postgresql-9.6.x86_64     1.7.0-0.el8     timescale_timescaledb 
```

**Actual behavior**
```
Available Packages
timescaledb-postgresql-10.x86_64     1.4.2-0.el8     timescale_timescaledb 
timescaledb-postgresql-9.6.x86_64     1.4.2-0.el8     timescale_timescaledb 
```

**Comment by hphde** [comment]
I think you are missing `timescaledb-postgresql-12.x86_64`, no? `timescaledb-postgresql-11.x86_64` is actually present

**Comment by msaladna** [comment]
I see the difference, and entirely my fault 🤦. 

In the [repo configuration](https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum) it's `baseurl=https://packagecloud.io/timescale/timescaledb/el/7/\$basearch` regardless of distribution release. In mine I changed **7** to **8** to match release major version, which contains the correct packages for all PostgreSQL releases except v12. Changing back to `el/7/` builds OK.

For clarity, symlink 8/ to 7/ if the packages are the same for vendor consistency?

Such that:

https://packagecloud.io/timescale/timescaledb/el/8 => https://packagecloud.io/timescale/timescaledb/el/7

**Comment by hphde** [comment]
I still wonder why for Centos8 timescaledb-postgresql-12 is missing

**Comment by RobAtticus** [comment]
Hi @hphde  @msaladna !

So what you found on packagecloud was actually a testing/staging area where I was experimenting with builds for CentOS 8 back during the 1.4.2 release. I never officially put up the instructions because I wasn't quite happy with the build process (so wasn't ready to commit to continuing it) and had not tested it fully besides.

I've gone ahead and uploaded new el8 packages for all PG versions to match 1.7.1 so if you are using this method, you should get the latest now. I will be refining the build process (and in fact some things upstream have improved making it much easier), so I should keep those up to date going forward.

**Comment by hphde** [comment]
@RobAtticus I was following the installation instructions on https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum

`timescaledb-postgresql-12` is now available but a dependency is missing:
```
dnf install -y timescaledb-postgresql-12
Last metadata expiration check: 0:03:08 ago on Wed 20 May 2020 06:58:37 AM CEST.
Error:
 Problem: conflicting requests
  - nothing provides timescaledb-tools >= 0.8 needed by timescaledb-postgresql-12-1.7.1-0.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by hphde** [comment]
A small hint @RobAtticus - if you put `EOL` in single-quotes there is no need to escape something inside the block.
```
sudo tee file <<'EOL'
echo $variable
EOL
```

**Comment by asoloviev89** [comment]
> @RobAtticus I was following the installation instructions on https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum
> 
> `timescaledb-postgresql-12` is now available but a dependency is missing:
> 
> ```
> dnf install -y timescaledb-postgresql-12
> Last metadata expiration check: 0:03:08 ago on Wed 20 May 2020 06:58:37 AM CEST.
> Error:
>  Problem: conflicting requests
>   - nothing provides timescaledb-tools >= 0.8 needed by timescaledb-postgresql-12-1.7.1-0.el8.x86_64
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```
> 
> `timescaledb-tools.x86_64` is `0.7.0-0.el8`

How did you solve this problem? I have this problem too. Followed the official instructions.

**Comment by RobAtticus** [comment]
Thanks @hphde and @asoloviev89 for reporting, I have published the latest timescaledb-tools for el8

**Comment by asoloviev89** [comment]
> Спасибо @hphde и @ asoloviev89 за сообщение, я опубликовал последние инструменты timescaledb для el8


Thanks for the support. The problem has changed. Initial data: 
```
CetOS 8, 
postgres (PostgreSQL) 12.1,
```
```
yum repository-packages timescale_timescaledb list --all
timescaledb-postgresql-10.x86_64                                                                          1.7.1-0.el8                                                                         timescale_timescaledb
timescaledb-postgresql-11.x86_64                                                                          1.7.1-0.el8                                                                         timescale_timescaledb
timescaledb-postgresql-12.x86_64                                                                          1.7.1-0.el8                                                                         timescale_timescaledb
timescaledb-postgresql-9.6.x86_64                                                                         1.7.1-0.el8                                                                         timescale_timescaledb
timescaledb-tools.x86_64                                                                                  0.8.1-0.el8                                                                         timescale_timescaledb
```
Part timescale_timescaledb.repo:
`baseurl=https://packagecloud.io/timescale/timescaledb/el/8/$basearch`

Error:
```
sudo yum install -y timescaledb-postgresql-12
package timescaledb-postgresql-12-1.7.1-0.el8.x86_64 requires postgresql12-server >= 12, but none of the                                                                                                 providers can be installed
  - conflicting requests
  - package postgresql12-server-12.0-1PGDG.rhel8.x86_64 is excluded
  - package postgresql12-server-12.1-1PGDG.rhel8.x86_64 is excluded
  - package postgresql12-server-12.1-2PGDG.rhel8.x86_64 is excluded
  - package postgresql12-server-12.2-1PGDG.rhel8.x86_64 is excluded
  - package postgresql12-server-12.2-2PGDG.rhel8.x86_64 is excluded
  - package postgresql12-server-12.3-1PGDG.rhel8.x86_64 is excluded
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
Tried to change `baseurl=https://packagecloud.io/timescale/timescaledb/el/8/$basearch` =
`baseurl=https://packagecloud.io/timescale/timescaledb/packages/el/8/$basearch`
got an error:
`Failed to download metadata for repo 'timescale_timescaledb'`

**Comment by asoloviev89** [comment]
my mistake was that when installing postgresql, I installed the repository for CentOS: `https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm`
And later I installed the repository from the instruction `https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum`: `https://download.postgresql.org/pub/repos/yum/12 /redhat/rhel-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm`
This is consequence of modular filtering (not a bug). Please see https://github.com/rpm-software-management/dnf/blob/master/doc/modularity.rst.

When module postgresql is enabled or default, all packages that has the same name with modular packages are excluded from all repositories. To disable modular filtering for certain repository, just add "`module_hotfixes=true`" into
 corresponding .repo file in `/etc/yum.repos.d/`.
Another way is described here:
http://micronetinternational.com/index.pl/en/00/https/people.planetpostgresql.org/devrim/index.php=3f/archives/100-Installing-PostgreSQL-on-RHEL-8.html
**Timescale has been installed.**

**Comment by dbech** [comment]
I still have this same issue every time I try to install TimescaleDB on Centos 8 with PostgreSQL12, anyone know how we can get the docs on the website updated?
