### ISSUE TITLE
Support for month, year and time zones in time_bucket

### ISSUE THREAD

**Issue by jean-francois-labbe** [timescale/timescaledb#414]
Time_bucket feature works great but why can't we use `SELECT time_bucket('1 month', date)...`

I would like to know how to get month bucket and even yearly buckets?

**Comment by solugebefola** [comment]
`time_bucket` is designed for regular intervals like days, hours, minutes.  As months and years are variable time units, the function does not support them.  A separate function that will deal with irregular time units is being considered, but for now, if you are trying to get a month long interval, you can use `30 days`.  Alternatively, you can use the PostgreSQL [date_trunc](https://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC) function which offers a less powerful version of the same functionality, but takes months and years (and decades and millenia...) as parameters.

**Comment by mmouterde** [comment]
@solugebefola `date_trunc` does not support Offsets as `time_bucket` do.
(Ex: make month starting on the 5th)

Do you know a workaround ?

**Comment by AndyMender** [comment]
@mmouterde if a "month" starts on the 5th of a calendar month, wouldn't it be sufficient to use `time_bucket("30 days", time)`?

On topic, `time_bucket("month", time)` would actually be nice, but would perhaps require either parsing the string representation of a time point, enums with set "month name = days" pairs or some other such approach.

**Comment by AndyMender** [comment]
@mmouterde yes, a trigger would also help with that, I think!

**Comment by webmastervishal** [comment]
Hey, any updates on this issue. 
When I used `time_bucket('30 days')` I got the weird results from the database table.
For now even 30 days isn't working fine or me.

**Comment by tmtron** [comment]
The [docs](https://docs.timescale.com/v1.1/using-timescaledb/reading-data#time-bucket) should really mention that it works only up to days.
When the docs say "more powerful version", we expect this command to do everything `date_trunc` can do plus some additional features.

**Comment by marioishikawa** [comment]
I also would like to see this working for at least up to a year, including months and quarters.

**Comment by lothar7** [comment]
I would love this feature. Its important to create monthly values when doing reporting.

**Comment by red-bin** [comment]
Adding my voice to the pile. At a technical level, I can appreciate why this functionality exists. At a practical level, though, I don't understand it at all. This lack of functionality has the effect of making timescaledb more of a hassle than it's worth, since I have to write my own code to handle months anyway. A separate function or wrapper could do wonders..

Please implement this functionality!

**Comment by cryptoflipper** [comment]
Yep, it's essential to have months and years, taking into account variable month lengths.

**Comment by tmtron** [comment]
@cryptoflipper Does this give different results, than the postgres [trunc](https://www.postgresql.org/docs/11/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC) function?

Also I wonder, if the [time_bucket](https://docs.timescale.com/v1.1/using-timescaledb/reading-data#time-bucket) function could just delegate to `trunc` when month, etc are specified (and maybe throw an error when the interval is not 1 in this case)

**Comment by benoist** [comment]
I'm getting these results with date_trunc in postgres 11, seems good to me or am I missing something

![image](https://user-images.githubusercontent.com/7202/66597751-e83ab600-eb9f-11e9-848c-3c197259b685.png)

**Comment by alsotop** [comment]
I think also a fairly big argument that hasn't yet been discussed on this issue is that `date_trunc` obviously does not support gap filling like you can get with the `time_bucket_gapfill` method available with TimescaleDB.

Is there anything in the roadmap for looking into adding this variable width time lengths/buckets? Or is this not something the team is looking at any time soon.

**Comment by bboule** [comment]
hey @alsotop  thanks for commenting I am just trying to wrap my head around what you are asking when you say variable width time buckets?  Could you give me an example?  Apologies for being a little slow on the uptake I just want to make sure I understand!

**Comment by alsotop** [comment]
@bboule Sorry for the confusion, I just meant variable width time buckets as in "months, quarters, years, etc" that are not currently supported since they're not regular intervals (i.e. September is only 30 days, but October is 31 days).

**Comment by bboule** [comment]
Ahh I see I was not making the connection thank you!!  So we are doing some product planning now and I think this makes sense...  Keep an eye on this issue as I hope to set a milestone (release target) for this in the next week or so as we work through the backlog... but this indeed does seem to have some momentum... if anyone on the thread is willing to share can you tell me a bit about your timescale use case that drives this (this is more for my own curiosity not as any sort of justification). @alsotop  thanks for clearing that up sometimes I am a little slow on the uptake :)

**Comment by jessicaaustin** [comment]
Here is our use case:

We are using timescale to store environment sensor data (for example, data from a weather station). It makes sense to compare these timeseries year-by-year to see trends in the seasonal statistics. For example, if we have a 20-year water temp timeseries, we calculate the average/min/max air temp in the month of March across all years, then when the user picks a specific year, they can compare that timeseries to the historic stats.

![Selection_263](https://user-images.githubusercontent.com/1159930/72478279-0ff07a00-379e-11ea-955b-0030f62bbca3.png)
*This chart shows that 2019 was one of the warmest years ever at this station.*

Currently we pull data from the db, calculate the statistics in python code, for weekly, monthly, and seasonal bins, and store those results. We're using pandas, [which offers a great range of offset options](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases) -- for example we use `Q-NOV` for our seasonal bins (winter=Nov,Dec,Jan; spring=Feb,Mar,Apr; etc). I tried doing this in timescale, but quickly ran into this issue and have been tracking it since. 

But here's the thing: **we are currently calculating stats one timeseries at a time. I see timescale coming in here and offering ways to quickly calculate stats like this across timeseries** -- for example, all water temp sensors in the gulf of mexico. That would be really powerful! And it's the kind of thing that would be very simple with postgis/timescale, compared to doing that with python/pandas.

**Comment by aguformoso** [comment]
@bboule thanks for diving into this.

My use case is creating Timescale Continuous Aggregates based on `time_bucket` in monthly and yearly resolutions, and have them aligned with 1st-of-month and 1st-of-year. I tried to accommodate my use case to doing `time_bucket('30 days' ... )` but as I ended up with mis-aligned buckets, I resorted to PostgreSQL's `date_trunc`. This also means I cannot manage my materialized view through Timescale, and it's a shame as Timescale does a _great_ job in managing materialized views.

**Comment by benoist** [comment]
@bboule we use timescale db for candle stick information. A monthly candle stick view is used a lot.

**Comment by bboule** [comment]
Hey guys this is really good stuff I really appreciate everyone taking the time to comment and share how this fits into the specific use cases (great learning for me as well)... I will make sure we have a goal for this as part of our planning within the next week or so via setting a milestone and will also add a comment as to some target dates as we work through this!!  Again THANK YOU guys and stay tuned!!!

**Comment by wrobell** [comment]
As stated in 2nd comment, `time_bucket` is designed for regular intervals. However, how will it behave in the context of leap seconds? Maybe with introduction of new functionality for variable width intervals, the behaviour could be documented.

**Comment by LloydAlbin** [comment]
Those that need this capability, while TimescaleDB works on this issue, can use this function that I wrote for my own project.

```
CREATE OR REPLACE FUNCTION tools.time_bucket (
  bucket_width interval,
  ts timestamptz
)
RETURNS TIMESTAMP WITH TIME ZONE AS
$body$
/*
millennium = 1000 years
century = 100 years
decade = 10 years
year = x year
months = x months

You may use any combination of years and months.
Example: 1 year 6 months aka 1.5 years
*/
DECLARE
  origin_ts timestamptz := '0001-01-01T00:00:00Z';
  months integer;
  bucket_months integer;
  bucket_month integer;
BEGIN
	IF bucket_width >= '1 month'::interval THEN
      bucket_months :=
          (EXTRACT(MONTH FROM bucket_width) + -- months	
          (EXTRACT(YEAR FROM bucket_width) * 12)); -- years
      months := (((EXTRACT(YEAR FROM ts)-EXTRACT(YEAR FROM origin_ts))*12)+EXTRACT(MONTH FROM ts)-1);
      bucket_month := floor(months/bucket_months)*bucket_months;
      
      RETURN make_timestamptz(
          (EXTRACT(YEAR FROM origin_ts)+floor(bucket_month/12))::integer, -- year
          (bucket_month%12)+1, -- month
          1, --day
          0, -- hour
          0, -- minute
          0 --second
          );
	ELSE
      RETURN public.time_bucket(bucket_width, ts);
    END IF;
END;
$body$
LANGUAGE 'plpgsql'
IMMUTABLE
RETURNS NULL ON NULL INPUT
SECURITY INVOKER;
```

**Comment by LloydAlbin** [comment]
I found a bug my my code, if you set a local timezone other than UTC. I have updated the function to correct this issue. I have now also included a timestamp and date version of this function.

timestaptz version of the function
```CREATE OR REPLACE FUNCTION tools.time_bucket (
  bucket_width interval,
  ts timestamptz,
  "offset" interval = '00:00:00'::interval,
  origin timestamptz = '0001-01-01 00:00:00+00'::timestamptz
)
RETURNS TIMESTAMPTZ AS
$body$
/*
millenium = 1000 years
century = 100 years
decade = 10 years
1.5 years aka 1 year 6 months or 18 months
year aka 12 months
half year aka 6 months
quarter aka 3 months
months = months
*/
DECLARE
  months integer;
  bucket_months integer;
  bucket_month integer;
BEGIN
	IF EXTRACT(MONTH FROM bucket_width) >= 1 OR EXTRACT(YEAR FROM bucket_width) >= 1 THEN
    origin := origin + ((0-date_part('timezone_hour', now()))::text || ' hours')::interval;
      bucket_months :=
          (EXTRACT(MONTH FROM bucket_width) + -- months	
          (EXTRACT(YEAR FROM bucket_width) * 12)); -- years
      months := (((EXTRACT(YEAR FROM ts)-EXTRACT(YEAR FROM origin))*12)+EXTRACT(MONTH FROM ts)-1);
      bucket_month := floor(months/bucket_months)*bucket_months;
      
      RETURN make_timestamptz(
          (EXTRACT(YEAR FROM origin)+floor(bucket_month/12))::integer, -- year
          (bucket_month%12)+1, -- month
          1, --day
          0, -- hour
          0, -- minute
          0, --second
          'Z');
	ELSE
      CASE 
      WHEN "offset" > '0s'::interval THEN
	      RETURN public.time_bucket(bucket_width, ts-"offset") + "offset";
      WHEN origin <> '0001-01-01T00:00:00Z'::timestamptz THEN
	      RETURN public.time_bucket(bucket_width, ts, origin);
      ELSE
	      RETURN public.time_bucket(bucket_width, ts);
      END CASE;
    END IF;
END;
$body$
LANGUAGE 'plpgsql'
IMMUTABLE
RETURNS NULL ON NULL INPUT
SECURITY INVOKER;
```

timestamp version of the function
```
CREATE OR REPLACE FUNCTION tools.time_bucket (
  bucket_width interval,
  ts timestamp,
  "offset" interval = '00:00:00'::interval,
  origin timestamp = '0001-01-01 00:00:00'::timestamp
)
RETURNS TIMESTAMP AS
$body$
/*
millenium = 1000 years
century = 100 years
decade = 10 years
1.5 years aka 1 year 6 months or 18 months
year aka 12 months
half year aka 6 months
quarter aka 3 months
months = months
*/
DECLARE
  months integer;
  bucket_months integer;
  bucket_month integer;
BEGIN
	IF EXTRACT(MONTH FROM bucket_width) >= 1 OR EXTRACT(YEAR FROM bucket_width) >= 1 THEN
      bucket_months :=
          (EXTRACT(MONTH FROM bucket_width) + -- months	
          (EXTRACT(YEAR FROM bucket_width) * 12)); -- years
      months := (((EXTRACT(YEAR FROM ts)-EXTRACT(YEAR FROM origin))*12)+EXTRACT(MONTH FROM ts)-1);
      bucket_month := floor(months/bucket_months)*bucket_months;
      
      RETURN make_timestamp(
          (EXTRACT(YEAR FROM origin)+floor(bucket_month/12))::integer, -- year
          (bucket_month%12)+1, -- month
          1, --day
          0, -- hour
          0, -- minute
          0 --second
          );
	ELSE
      CASE 
      WHEN "offset" > '0s'::interval THEN
	      RETURN public.time_bucket(bucket_width, ts-"offset") + "offset";
      WHEN origin <> '0001-01-01T00:00:00'::timestamp THEN
	      RETURN public.time_bucket(bucket_width, ts, origin);
      ELSE
	      RETURN public.time_bucket(bucket_width, ts);
      END CASE;
    END IF;
END;
$body$
LANGUAGE 'plpgsql'
IMMUTABLE
RETURNS NULL ON NULL INPUT
SECURITY INVOKER;
```

date version of the function
```
CREATE OR REPLACE FUNCTION tools.time_bucket (
  bucket_width interval,
  ts date,
  "offset" interval = '00:00:00'::interval,
  origin date = '0001-01-01'::date
)
RETURNS DATE AS
$body$
/*
millenium = 1000 years
century = 100 years
decade = 10 years
1.5 years aka 1 year 6 months or 18 months
year aka 12 months
half year aka 6 months
quarter aka 3 months
months = months
*/
DECLARE
  months integer;
  bucket_months integer;
  bucket_month integer;
BEGIN
	IF EXTRACT(MONTH FROM bucket_width) >= 1 OR EXTRACT(YEAR FROM bucket_width) >= 1 THEN
      bucket_months :=
          (EXTRACT(MONTH FROM bucket_width) + -- months	
          (EXTRACT(YEAR FROM bucket_width) * 12)); -- years
      months := (((EXTRACT(YEAR FROM ts)-EXTRACT(YEAR FROM origin))*12)+EXTRACT(MONTH FROM ts)-1);
      bucket_month := floor(months/bucket_months)*bucket_months;
      
      RETURN make_date(
          (EXTRACT(YEAR FROM origin)+floor(bucket_month/12))::integer, -- year
          (bucket_month%12)+1, -- month
          1 --day
          );
	ELSE
      CASE 
      WHEN "offset" > '0s'::interval THEN
	      RETURN public.time_bucket(bucket_width, ts-"offset") + "offset";
      WHEN origin <> '0001-01-01'::date THEN
	      RETURN public.time_bucket(bucket_width, ts, origin);
      ELSE
	      RETURN public.time_bucket(bucket_width, ts);
      END CASE;
    END IF;
END;
$body$
LANGUAGE 'plpgsql'
IMMUTABLE
RETURNS NULL ON NULL INPUT
SECURITY INVOKER;
```

**Comment by frickenate** [comment]
+1 to the use case presented by @aguformoso - `time_bucket('month')` and `time_bucket('year')` support with `CREATE VIEW` for continuous aggregates. Practically every query we need to run is for monthly, yearly, or all-time data, and it's horribly inefficient to be querying at `SELECT` time from daily values only.

The lack of support for this is a real pain.

**Comment by RagunovichVlad** [comment]
@LloydAlbin thanks! and do you have gapfill version?

**Comment by pwebbitrs** [comment]
I'm also keen to see efficient calendar month bucketing ( and  cal/years but  cal months are more applicable to us).    Often from a reporting pov people care about calendar months not 30 day intervals.  I can fully understand why days / fixed time periods are only supported technically, however if you are chunking by time anyway, it doesn't sound like a particularly unsolveable problem and I think there would be a **lot** of interest.

**Comment by ricky-sb** [comment]
Any suggestions on the most efficient way to do a gapfill with @LloydAlbin's version? I've been using a CTE with `generate_series` and JOINing them, but I feel like there's probably a better way.

**Comment by LloydAlbin** [comment]
The CTE is the fastest way within Postgres itself. The TimescaleDB extension does the gapfill faster than the CTE as I have tested both for doing the time periods that TimescaleDB supports. For the time periods that TimescaleDB does not support, then the CTE will be faster as you TimescaleDB would have to be generating a lot of extra date/time’s that will later on be thrown away during the conversion from day to month or day to year, etc. The best solution would be to update the TimescaleDB extension to support the month, year, etc time_bucket long with their respective gapfill’s. I just have not had any free time to do this myself and submit it as a patch. My code was just to prove it was theoretically possible to do, since the TimescaleDB people said it was impossible, and should be rewritten into C to be used in the TimescaleDB  extension.

**Comment by Zoundream** [comment]
>  I will make sure we have a goal for this as part of our planning within the next week or so via setting a milestone and will also add a comment as to some target dates as we work through this!! Again THANK YOU guys and stay tuned!!!

Has there been any progress in adding this feature to a milestone ? 
The quoted text above was from mid-January. 
Apologies in advance for the noise if this feature is already scheduled to a milestone and I could not find it.

**Comment by bonesoul** [comment]
+1 on this, any etas?

**Comment by pojpojpoj** [comment]
+1 on this aswell. Need to group my consumption usage on monthly intervals, not 30 days :) Looking forward to this.

**Comment by bacheson** [comment]
it's crazy this isn't implemented...for anyone doing even basic analytics, monthly reporting periods are a day 1 requirement...this is holding me back from rolling out a massive timescale cloud cluster

**Comment by GlennMatthys** [comment]
If you can make time_bucket accept an expression when creating the continuous aggregate, this problem would be solved. An example where I have a `tsms` column with timestamp in milliseconds, aggregated by month:

```
time_bucket(bigint '1', (EXTRACT(
		'epoch' FROM date_trunc('month', to_timestamp(tsms / 1000) AT TIME ZONE 'Europe/Brussels')
			AT TIME ZONE 'Europe/Brussels'
	) * 1000)::bigint)
```

But that just returns `ERROR:  time_bucket function for continuous aggregate query should be called on the dimension column of the hypertable ` now.

**Comment by mfreed** [comment]
Thanks, everybody.  This is definitely a feature request we have heard, just haven't yet been able to prioritize/schedule it against other things.

We definitely are open to community contributions here!  =)

**Comment by bonesoul** [comment]
I tried replacing time_bucket with date_trunc

```
CREATE VIEW cagg_steam_stats_monthly WITH (timescaledb.continuous, timescaledb.refresh_interval = '1h') AS
SELECT game_id,
DATE_TRUNC('month', time) as time,
round(avg(x))::int as x
from stats
group by 1,2;
```

but getting

`no valid bucketing function found for continuous aggregate query`

any ideas?

**Comment by GlennMatthys** [comment]
> I tried replacing time_bucket with date_trunc while creating a cagg
> 
> ```
> CREATE VIEW cagg_stats_monthly WITH (timescaledb.continuous, timescaledb.refresh_interval = '1h') AS
> SELECT id,
> DATE_TRUNC('month', time) as time,
> round(avg(x))::int as x
> from stats
> group by 1,2;
> ```
> 
> but getting
> 
> `no valid bucketing function found for continuous aggregate query`
> 
> then tried
> 
> ```
> CREATE VIEW cagg_stats_monthly WITH (timescaledb.continuous, timescaledb.refresh_interval = '1h') AS
> SELECT id,
> time_bucket('30 days', DATE_TRUNC('month', time)) as time,
> round(avg(x))::int as x
> from stats
> group by 1,2;
> ```
> 
> `time_bucket function for continuous aggregate query should be called on the dimension column of the hypertable `
> 
> any ideas?

You have to use time_bucket with the "time" column of your table. There's no way around it.

**Comment by franck102** [comment]
Can we know what the exact requirements are for alternate time_bucket functions?

The function below returns a timestamptz, it has the same options as the original time_bucket function, and yet I get that "no valid bucketing function found" error when trying to use it to create a CT.
The function works like a charm to create a regular (non CT) view.

Thanks!

```
create or replace view metering."service:decisions:hourly" WITH (timescaledb.continuous) AS 
select metering.time_bucket(interval '1 hour', time) as time, series_id, sum(value) 
from metering."service:decisions:increase" 
group by metering.time_bucket(interval '1 hour', time), series_id
```

```
CREATE OR REPLACE FUNCTION metering.time_bucket(bucket_width interval, ts timestamp with time zone, "offset" interval DEFAULT '00:00:00'::interval, origin timestamp with time zone DEFAULT '0001-01-01 00:09:21+00:09:21'::timestamp with time zone)
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE STRICT
AS $function$
/*
millenium = 1000 years
century = 100 years
decade = 10 years
1.5 years aka 1 year 6 months or 18 months
year aka 12 months
half year aka 6 months
quarter aka 3 months
months = months
*/
DECLARE
  months integer;
  bucket_months integer;
  bucket_month integer;
BEGIN
	IF EXTRACT(MONTH FROM bucket_width) >= 1 OR EXTRACT(YEAR FROM bucket_width) >= 1 THEN
    origin := origin + ((0-date_part('timezone_hour', now()))::text || ' hours')::interval;
      bucket_months :=
          (EXTRACT(MONTH FROM bucket_width) + -- months
          (EXTRACT(YEAR FROM bucket_width) * 12)); -- years
      months := (((EXTRACT(YEAR FROM ts)-EXTRACT(YEAR FROM origin))*12)+EXTRACT(MONTH FROM ts)-1);
      bucket_month := floor(months/bucket_months)*bucket_months;

      RETURN make_timestamptz(
          (EXTRACT(YEAR FROM origin)+floor(bucket_month/12))::integer, -- year
          (bucket_month%12)+1, -- month
          1, --day
          0, -- hour
          0, -- minute
          0, --second
          'Z');
	ELSE
      CASE
      WHEN "offset" > '0s'::interval THEN
	      RETURN public.time_bucket(bucket_width, ts-"offset") + "offset";
      WHEN origin <> '0001-01-01T00:00:00Z'::timestamptz THEN
	      RETURN public.time_bucket(bucket_width, ts, origin);
      ELSE
	      RETURN public.time_bucket(bucket_width, ts);
      END CASE;
    END IF;
END;
$function$
;
```

**Comment by greatbn** [comment]
Hi @franck102,

I created the function as you mentioned above. But when I create a view, I got the error `ERROR:  no valid bucketing function found for continuous aggregate query`. 

My data like this 

```
usages=# select * from usage limit 1;
       timestamp        |   user_id    |   bucket_name    |  bucket_size  | egress_datatransfer | total_objects 
------------------------+--------------+------------------+---------------+---------------------+---------------
 2020-10-10 17:38:55+00 | user1 | bucket1 | 1200378576896 |       4137120396308 |     208727197
```

The `create view` command 

```
CREATE VIEW cagg_usage_view_1month WITH
(timescaledb.continuous, timescaledb.refresh_interval = '30m')
AS
SELECT user_id, bucket_name, metering.time_bucket('1 months', timestamp) as time,
       avg(bucket_size) as usage
 FROM usage
  GROUP BY user_id, bucket_name, metering.time_bucket('1 months', timestamp);
```

Thank you!

**Comment by franck102** [comment]
> Hi @franck102,
> 
> I created the function as you mentioned above. But when I create a view, I got the error `ERROR: no valid bucketing function found for continuous aggregate query`.

Well yes, that’s exactly the problem I reported. You can create a regular view (without times aledb.continuous), but not a continuous aggregate view 👎

**Comment by Greenbones** [comment]
Just echoing my support for this feature, our org needs calendar based monthly/yearly aggregation support as well.

**Comment by qwAAQ** [comment]
Is this being worked on? My entire solution hangs on being to use the 'quarter' feature which is available in date_trunc. I also chose TimescaleDB due to the continuous aggregates.

**Comment by RedShift1** [comment]
> Is this being worked on? My entire solution hangs on being to use the 'quarter' feature which is available in date_trunc. I also chose TimescaleDB due to the continuous aggregates.

I've solved this by using triggers on insert to keep totals over monthly, quarterly, etc... periods.

**Comment by qwAAQ** [comment]
> > Is this being worked on? My entire solution hangs on being to use the 'quarter' feature which is available in date_trunc. I also chose TimescaleDB due to the continuous aggregates.
> 
> I've solved this by using triggers on insert to keep totals over monthly, quarterly, etc... periods.

Yeah I have thought about this too. I just see no use case for TimescaleDB anymore if I were to create triggers for the tables to just continuously insert convert data to quarter time buckets in another table. My data is static so a trigger would definitely solve it. I'm just wondering if TimescaleDB will support this anytime soon.

**Comment by boris-hocde** [comment]
Hey, I would really love this feature too.

For now, I'm using 12 equally divided parts of the year to build "monthly" continuous aggregate. This is definitely inaccurate, but I could not find a better solution.

```sql
CREATE MATERIALIZED VIEW event_aggregate WITH (timescaledb.continuous) AS
SELECT time_bucket(INTERVAL '30.4375 days', time, origin => '2000-01-01') AS bucket,
       SUM(my_event) AS sum_events
FROM event_raw
GROUP BY bucket;
```

`origin` set to `2000-01-01` to make it start at the beginning of a month instead of a week. See the warning in [the ref](https://docs.timescale.com/latest/api#time_bucket).

**Comment by dberardo-com** [comment]
@boris-hocde are the results that you are showing there starting from the first of a month just because your query interval happens to start on the 1th of January or is it always going to be the case?

**Comment by darthsiderius** [comment]
Looks like InfluxDB supports this , given that the feature has been open for 3 years and lack of activity - im just going to migrate.

**Comment by afiskon** [comment]
As I understand the main use case for `SELECT time_bucket('1 month', date) ...` are continuous aggregates. One possible workaround is to build a regular (or MATERIALIZED) VIEW on top of aggregate, like this:

```
CREATE MATERIALIZED VIEW conditions_summary_daily
WITH (timescaledb.continuous) AS
SELECT device,
       time_bucket(INTERVAL '1 day', tstamp) AS bucket,
       SUM(temperature) as sum, count(*) as num,
       MAX(temperature) as max,
       MIN(temperature) as min
FROM conditions
GROUP BY device, bucket;

CREATE VIEW conditions_summary_monthly
AS
SELECT device,
       date_trunc('month', bucket) AS month,
       sum(sum)/sum(num) as avg,
       MAX(max) as max,
       MIN(min) as min
FROM conditions_summary_daily
GROUP BY device, month;
```

By looking at `EXPLAIN` for queries like `select * from conditions_summary_monthly where month = '2021-02-01';` it seems that this approach is quite efficient.

**Comment by dberardo-com** [comment]
i have also implemented something similar. 

do you feel like sharing the details of the EXPLAIN query so i could compare that to my implementation and see if i have some bugs in it? @afiskon 

i said this because my query on the aggregate seems to be actually quite slow and i wonder why, since the number of rows on the aggregate are very few, and the ones on the non/aggregated time windows are not that many either.

**Comment by afiskon** [comment]
@dberardo-com Sure! Here is a complete gist https://gist.github.com/afiskon/fcd355a087d1f7cc8840952f03cd725e

One reason why your queries might be slow is that by default continuous aggregates merge "hot" data to the result as well, thus if you are SELECT'ing the data for which there is no aggregate yet, you are calculating it dynamically. More details are in the docs https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates

Another thing worth checking is that your PostgreSQL instance was optimized for the given hardware. The best way to make sure of that is to run `timescaledb-tune` https://docs.timescale.com/latest/using-timescaledb/tooling#ts-tune

The reason why I'm not using AVG for the second VIEW is that there is no way you can calculate the right AVG value from another aggregate unless it's a (sum, count) pair or a complete list of original values. I.e. AVG(ACG(x), AVG(y), ...) is meaningless.

If you need any further help please address the community slack https://slack.timescale.com/ I suspect that GitHub is not the right place for this. Good luck!

**Comment by afiskon** [comment]
Corresponding survey / discussion: https://github.com/timescale/timescaledb/discussions/3258

**Comment by Kl-Li** [comment]
nomizo to 1o gia emas. sosta?

**Comment by noctarius** [comment]
@afiskon the problem with daily aggregation is, that the days are still wrong. If your timestamp is at UTC, but the day in your timezone starts at UTC+12, all results are shifted by half a day.

**Comment by tmtron** [comment]
Postgres 14 has a new function [date_bin](https://www.postgresql.org/docs/14/functions-datetime.html#FUNCTIONS-DATETIME-BIN) which does exactly what we need in our project - so finally we can get rid of [time_bucket](https://docs.timescale.com/api/latest/analytics/time_bucket) and some nasty workarounds.

**Comment by pfried** [comment]
@tmtron @afiskon As this is a common use case is there any chance you could share a gist on this?

**Comment by LloydAlbin** [comment]
Actually, when you look at the Postgres 14 docs, it looks like the date_bin does not fix the month, quarter, year, decade, century, millennium issue. So we still need to use a wrapper function that switches between date_bin and date_trunc to deal with dates properly.

date_bin(stride, source, origin)
The stride interval cannot contain units of month or larger.

**Comment by milosjovac** [comment]
@LloydAlbin tnx for the wrapper function. I was wondering if you maybe have something similar for `time_bucket_gapfill`? Or would it be enough to just replace the timescale `time_bucket` function calls with `time_bucket_gapfill`?

**Comment by elpablete** [comment]
Hey guy, just my 2 cents: weeks are convertible to days (unlike months, years ...) shouldn't it be possible to specify the interval in weeks?

**Comment by AuspeXeu** [comment]
Is there also going to be a equivalent `*_ng` version of `gapfill`?

**Comment by olivermack** [comment]
For clarification: should `time_bucket_ng` in 2.5.0 already support monthly and yearly buckets in combination with continuous aggregates? I was not able to find information about that in the documentation about `time_bucket_ng` - all it says in [the docs](https://docs.timescale.com/api/latest/hyperfunctions/time_bucket_ng/#sample-usage) is:

> You can use time_bucket_ng() with continuous aggregates

... but the sample shows only the usage with `timescaledb_experimental.time_bucket_ng('7 days', day) AS bucket`.

Actually, using the sample provided in the docs, it raises

```
CREATE MATERIALIZED VIEW conditions_summary_monthly
WITH (timescaledb.continuous) AS
SELECT city,
       timescaledb_experimental.time_bucket_ng('1 month', day) AS bucket,
       MIN(temperature),
       MAX(temperature)
FROM conditions
GROUP BY city, bucket;
---
ERROR:  months and years not supported
DETAIL:  An interval must be defined as a fixed duration (such as weeks, days, hours, minutes, seconds, etc.).
```

Executing the following query yields a proper result though:

```
SELECT city,
       timescaledb_experimental.time_bucket_ng('1 month', day) AS bucket,
       MIN(temperature),
       MAX(temperature)
FROM conditions
GROUP BY city, bucket;
``` 

| city   | bucket     | min | max |
|--------|------------|-----|-----|
| Moscow | 2021-06-01 |  22 |  34 |

---

FYI: `SELECT extversion FROM pg_extension where extname = 'timescaledb';` 

| extversion |
|------------|
| 2.5.0      |


--- 

I'd appreciate any clarification on that.

**Comment by afiskon** [comment]
@olivermack Thanks for the question.

Yes, I guess the documentation is a bit confusing. The reason is that  time_bucket_ng() and CAGGs are separate entities. **time_bucket_ng()** does support months, and can be used in caggs, as the documentation says. However, it doesn't mean that **CAGGs** support monthly buckets. I will add an entry to time_bucket_ng() documentation to clarify this.

The support of monthly buckets for CAGGs is currently on review https://github.com/timescale/timescaledb/pull/3753 We expect it to be released in 2.6.0. Also, it's possible to build TS from the source code with monthly buckets support, but I wouldn't recommend it unless you want to be an early adopter of the experimental feature and give us your feedback.

**Comment by afiskon** [comment]
@pfried Thanks for the question and sorry for the late reply.

Since time_bucket_ng() is an experimental function, we prefer not to promise any particular behavior in respect of timezones, until it stabilizes and will be promoted from the experimental schema. This is why this behavior is not well documented.

Internally it's very simple: it treats the time in given TZ as if it was in UTC.  You can find a little more information in the source code and the tests if you are really interested in this topic, just look for "time_bucket_ng" and you will easily find it, e.g. https://github.com/timescale/timescaledb/blob/master/src/time_bucket.c#L470 

CAGGs don't currently support timezones. We are currently focusing on adding monthly buckets support to CAGGs. See my answer above.

**Comment by pe224** [comment]
@afiskon

I just upgraded to TimescaleDB 2.6.0 and was trying out the following (simplified) continuous aggregate
```sql
CREATE MATERIALIZED VIEW device_data_monthly
WITH (timescaledb.continuous)
AS
SELECT
    timescaledb_experimental.time_bucket_ng('1 month', time) as bucket
    ,device_id
    ,avg(temp) AS temperature
    ,count(*) AS num_points
FROM
    device_data
GROUP BY bucket, device_id
WITH NO DATA
```

I am receiving the error
```
continuous aggregate view must include a valid time bucket function
```

I saw your PR for monthly buckets in CAGGs landed in master on Dec 31st and the docs mention availability from v2.6.0 on.
What am I doing wrong?

**Comment by jflambert** [comment]
+1 for month support in time_buckets, so I can use it in a cagg

**Comment by kamilgregorczyk** [comment]
time_bucket_ng doesn't work in continous aggregates :/

**Comment by dberardo-com** [comment]
> time_bucket_ng doesn't work in continous aggregates :/

@svenklemm does it work now?

**Comment by svenklemm** [comment]
@dberardo-com time_bucket_ng is getting phased out but all the features were added to the normal time_bucket functions. Which feature are you looking for? You can use timezones and monthly buckets in caggs now.

**Comment by dberardo-com** [comment]
thanks for pointing that out. i will have a look at the documentation then.

**Comment by jfjoly** [comment]
JF here, the director of product from Timescale responsible for releasing the time_bucket upgrade. 
In short, support for time zones and bucketing by weekly, monthly, yearly, or even a century interval using the `time_bucket` hyperfunction is finally available in TimescaleDB 2.8. 

This was our # 1 most requested feature. Also, a lot of you commented and/or reacted to this GitHub issue and I’m eager to hear your feedback on it.

Have any of you tried out the new feature? If so, it would be great to get your feedback on these new features and if they solved your problem.

**Comment by jflambert** [comment]
Hi @jfjoly, I ran some quick tests with the monthly `time_bucket` option and it works great, as expected.

Having said that, I already had a workaround which worked fine, and switching over to your native implementation actually seems a bit slower. Here's my very basic test bench. Let me know if I'm doing anything wrong.

```
create table test_monthly_buckets
(
  timestamp timestamptz PRIMARY KEY
);

select create_hypertable('test_monthly_buckets', 'timestamp');

insert into test_monthly_buckets (timestamp) select generate_series('1990-01-01', '2000-01-01', '1 hour'::INTERVAL);
insert into test_monthly_buckets (timestamp) select generate_series('2000-01-01 00:01:00', '2010-01-01', '1 minute'::INTERVAL);
insert into test_monthly_buckets (timestamp) select generate_series('2010-01-01 00:00:01', '2020-01-01', '30 second'::INTERVAL);

-- ~7s to complete
WITH daily_buckets AS
(
  SELECT TIME_BUCKET('1 day', timestamp) AS day,
    date_trunc('month', timestamp) AS month,
    COUNT(timestamp) AS daily_count
  FROM test_monthly_buckets
  GROUP BY day, month
)
SELECT month, SUM(daily_count) AS monthly_count
FROM daily_buckets
GROUP BY month
ORDER BY month;

-- ~12s to complete
SELECT TIME_BUCKET('1 month', timestamp) AS month,
  COUNT(timestamp) AS monthly_count
FROM test_monthly_buckets
GROUP BY month
ORDER BY month;
```

**Comment by RedShift1** [comment]
> 

Can you provide more information such as Postgres version and the output of EXPLAIN ANALYZE?

**Comment by jflambert** [comment]
@RedShift1 I use `timescale/timescaledb-ha:pg13.8-ts2.8-latest`

Explain analyze
- [CTE hack](https://explain.depesz.com/s/Iu4c)
- [monthly bucket](https://explain.depesz.com/s/S1Ba)

**Comment by noctarius** [comment]
@jflambert can you please retry the `time_bucket` with `jit=off` (just-in-time compilation disabled) in the session and see if that optimizes the speed?

**Comment by jflambert** [comment]
@noctarius somewhat better, it finishes in ~10s instead of ~12s

[monthly bucket with jit=off](https://explain.depesz.com/s/26Xm)

**Comment by urlmonitor** [comment]
@jfjoly Timebuckets themselves work fine. However, the policies do not work.
I get "The start and end offsets must cover at least two buckets in the valid time range of type "timestamp with time zone""
My settings are 
        'bucket_interval': '1 year',
        'start_offset': '4 years',
        'end_offset': '2 years',
        
Is this a known bug? Or is it me? 
Using timescaledb 2.14.2
