### ISSUE TITLE
[Bug]: "out of shared memory" when deleting many old rows

### ISSUE THREAD

**Issue by spiralw** [timescale/timescaledb#5075]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

We have a hypertable that stores some metadata on sent messages on a chat platform, keyed by message ID. When someone individually deletes (rather than bulk delete) many old messages at the same time, timescaledb throws "out of shared memory" error.
I have tried raising `shared_buffers` value, but this doesn't fix the issue; there is a lot of free memory on our database server, so I could try giving it more, but it doesn't seem to be doing anything.
Keep in mind I can't use the `timescaledb-tune` automatic tuning tool, since there are other databases running on the same machine and most of the data stored in this database is used very rarely, so it shouldn't be cached.
The table is not compressed.

Table definition:
```sql
create table messages (
    mid bigint not null primary key,
    -- etc
);

select create_hypertable('messages', 'mid', chunk_time_interval => 362387865600000);
```

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.6

### What operating system did you use?

debian 11

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Dec 10 18:58:25 db postgres[681630]: 2022-12-10 17:58:25.831 UTC [681630] ERROR:  out of shared memory
Dec 10 18:58:25 db postgres[681630]: 2022-12-10 17:58:25.831 UTC [681630] HINT:  You might need to increase max_locks_per_transaction.
Dec 10 18:58:25 db postgres[681630]: 2022-12-10 17:58:25.831 UTC [681630] STATEMENT:  DELETE FROM "messages" WHERE "mid" = $1
```

### How can we reproduce the bug?

I don't know how to reproduce this issue outside of our production environment.

**Comment by sb230132** [comment]
Hi @spiralw 
I could not reproduce the crash when i change the variable. Please provide more details on this issue.

```
postgres281=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.8.1   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

postgres281=# show timescaledb.telemetry_level ;
 timescaledb.telemetry_level
-----------------------------
 basic
(1 row)

postgres281=# set timescaledb.telemetry_level to OFF;
SET
postgres281=# show timescaledb.telemetry_level ;
 timescaledb.telemetry_level
-----------------------------
 off
(1 row)

postgres281=# set timescaledb.telemetry_level to 1234;
ERROR:  invalid value for parameter "timescaledb.telemetry_level": "1234"
HINT:  Available values: off, no_functions, basic.
postgres281=# show timescaledb.telemetry_level ;
 timescaledb.telemetry_level
-----------------------------
 off
(1 row)
```

**Comment by spiralw** [comment]
@sb230132 Thanks for your reply. The reason why the `chunk_time_interval` is so high is because our `mid` row is not an unix timestamp. We do have multiple chunks:

```sql
messages=# select show_chunks('messages');
                show_chunks                
-------------------------------------------
 _timescaledb_internal._hyper_1_1608_chunk
 _timescaledb_internal._hyper_1_1609_chunk
 _timescaledb_internal._hyper_1_1610_chunk

...

 _timescaledb_internal._hyper_1_3219_chunk
 _timescaledb_internal._hyper_1_3220_chunk
 _timescaledb_internal._hyper_1_3221_chunk
(1614 rows)
```

The hypertable has ~1.6 billion rows in total, so each chunk has ~100 million rows. Is this too many rows per chunk?

**Comment by sb230132** [comment]
Hi @spiralw 
Thanks for the clarification. I would like to understand more about boundaries of those chunks.

When i create a hypertable with time dimension column being a bigint. I see that chunk interval ranges from 0 to 362387865600000.

```
postgres281=# SELECT create_hypertable('tt2', 'id', chunk_time_interval => 362387865600000);
postgres281=#
postgres281=# \d+ _timescaledb_internal._hyper_5_9_chunk
                                     Table "_timescaledb_internal._hyper_5_9_chunk"
 Column |           Type           | Collation | Nullable | Default | Storage | Compression | Stats target | Description
--------+--------------------------+-----------+----------+---------+---------+-------------+--------------+-------------
 id     | bigint                   |           | not null |         | plain   |             |              |
 time   | timestamp with time zone |           | not null |         | plain   |             |              |
 cpu    | double precision         |           |          |         | plain   |             |              |
Indexes:
    "_hyper_5_9_chunk_tt2_id_idx" btree (id DESC)
    "_hyper_5_9_chunk_tt2_time_idx" btree ("time" DESC)
Check constraints:
    "constraint_9" CHECK (id >= '0'::bigint AND id < '362387865600000'::bigint)
```
Can you share output of
\d+ _timescaledb_internal._hyper_1_1608_chunk
\d+ _timescaledb_internal._hyper_1_1610_chunk
\d+ _timescaledb_internal._hyper_1_3219_chunk

**Comment by spiralw** [comment]
@sb230132 Sure:

<details><summary>_timescaledb_internal._hyper_1_1608_chunk</summary>

```
messages=#  \d+ _timescaledb_internal._hyper_1_1608_chunk
                              Table "_timescaledb_internal._hyper_1_1608_chunk"
    Column    |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
--------------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 mid          | bigint  |           | not null |         | plain   |             |              | 
 channel      | bigint  |           | not null |         | plain   |             |              | 
 member       | integer |           |          |         | plain   |             |              | 
 sender       | bigint  |           | not null |         | plain   |             |              | 
 original_mid | bigint  |           |          |         | plain   |             |              | 
 guild        | bigint  |           |          |         | plain   |             |              | 
Indexes:
    "1608_1608_messages_pkey" PRIMARY KEY, btree (mid)
Check constraints:
    "constraint_1608" CHECK (mid >= '1038603622809600000'::bigint AND mid < '1038966010675200000'::bigint)
Inherits: messages
Access method: heap
```
</details>

<details><summary>_timescaledb_internal._hyper_1_1610_chunk</summary>

```
messages=#  \d+ _timescaledb_internal._hyper_1_1610_chunk
                              Table "_timescaledb_internal._hyper_1_1610_chunk"
    Column    |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
--------------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 mid          | bigint  |           | not null |         | plain   |             |              | 
 channel      | bigint  |           | not null |         | plain   |             |              | 
 member       | integer |           |          |         | plain   |             |              | 
 sender       | bigint  |           | not null |         | plain   |             |              | 
 original_mid | bigint  |           |          |         | plain   |             |              | 
 guild        | bigint  |           |          |         | plain   |             |              | 
Indexes:
    "1610_1610_messages_pkey" PRIMARY KEY, btree (mid)
Check constraints:
    "constraint_1610" CHECK (mid >= '1038966010675200000'::bigint AND mid < '1039328398540800000'::bigint)
Inherits: messages
Access method: heap
```
</details>

<details><summary>_timescaledb_internal._hyper_1_3219_chunk</summary

```
messages=#  \d+ _timescaledb_internal._hyper_1_3219_chunk
                              Table "_timescaledb_internal._hyper_1_3219_chunk"
    Column    |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
--------------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 mid          | bigint  |           | not null |         | plain   |             |              | 
 channel      | bigint  |           | not null |         | plain   |             |              | 
 member       | integer |           |          |         | plain   |             |              | 
 sender       | bigint  |           | not null |         | plain   |             |              | 
 original_mid | bigint  |           |          |         | plain   |             |              | 
 guild        | bigint  |           |          |         | plain   |             |              | Indexes:
    "3219_3219_messages_pkey" PRIMARY KEY, btree (mid)
Check constraints:
    "constraint_3219" CHECK (mid >= '1038241234944000000'::bigint AND mid < '1038603622809600000'::bigint)
Inherits: messages
Access method: heap
```

</details>

As an example, a `mid` at the start of the table could be `467790350841544707`, and a `mid` of a message sent right now could be `1052191574974545980`.

Now that I think about it, yes, this is Twitter snowflake format, I completely forgot about it until now.

**Comment by sb230132** [comment]
Hi @spiralw
Can you please let me know the current value of max_locks_per_transaction.
As suggested in error message, can you increase max_locks_per_transaction and check the behaviour.

**Comment by spiralw** [comment]
That is set to the default, we don't run multiple queries in the same transaction. I can try raising it though

**Comment by spiralw** [comment]
I just tried raising the `max_locks_per_transaction` (to 256, from the default of 64 - please let me know if you suggest another value) but this did not stop the errors.

Sorry, I don't know how I would make a reproducible scenario for this outside of our production environment.

**Comment by spiralw** [comment]
If it helps, here is our postgresql.conf: https://github.com/PluralKit/infra/blob/main/config/postgresql.messages.conf

I checked our grafana dashboard and during the times that timescaledb printed the "out of shared memory" error, delete queries also were taking way too long:
![20221215_22h52m08s_grim](https://user-images.githubusercontent.com/64013111/208018225-24a785e2-98ef-4d83-b027-a0b347a0e218.png)

(red/blue are "delete single row in messages table" and "delete multiple rows in messages table", respectively)

During that time, insert queries did not have a spike in query time, but did sometimes also fail with "out of shared memory" error.

**Comment by svenklemm** [comment]
Can you provide more information on the `DELETE` queries you are running, seems like there is no chunk exclusion happening leading to the increased query time and increased lock requirements,

**Comment by spiralw** [comment]
Hi, we are running the following queries:

- `DELETE FROM "messages" WHERE "mid" = $1`
- `DELETE FROM "messages" WHERE "mid" IN ($1, $2, ... $n)`

**Comment by spiralw** [comment]
Hi @fabriziomello, happy new year. Here is the output of that command:
```
messages=*> EXPLAIN (BUFFERS, ANALYZE)  DELETE FROM "messages" WHERE "mid" = 926699253580046369;
                                                                              QUERY PLAN                                                                               
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (HypertableModify)  (cost=0.43..8.45 rows=1 width=10) (actual time=0.265..0.266 rows=0 loops=1)
   Buffers: shared read=3
   ->  Delete on messages  (cost=0.43..8.45 rows=1 width=10) (actual time=0.265..0.266 rows=0 loops=1)
         Delete on _hyper_1_2801_chunk messages_1
         Buffers: shared read=3
         ->  Index Scan using "2801_2801_messages_pkey" on _hyper_1_2801_chunk messages_1  (cost=0.43..8.45 rows=1 width=10) (actual time=0.264..0.264 rows=0 loops=1)
               Index Cond: (mid = '926699253580046369'::bigint)
               Buffers: shared read=3
 Planning:
   Buffers: shared hit=55175 read=2718 dirtied=1
 Planning Time: 294.752 ms
 Execution Time: 0.298 ms
(12 rows)
```

**Comment by spiralw** [comment]
I disabled the code that was running delete queries, since the errors were getting unsustainable. It did not throw an "out of shared memory" error when running the example query.
Sorry, I'm not sure of a good example of the `WHERE "mid" in (...)` query that I could try running against the production database. All of our queries are generated in response to user actions - as a worst case scenario, it's possible (but uncommon) that a user might run a bulk delete for 100 messages, where each `mid` value would map to a different chunk, but with no rows existing in the database for any of them.

**Comment by fabriziomello** [comment]
@spiralw I understand. Are u able to upgrade this instance to 2.9.1 and see if it improve things (we fixed some memory and cache issues in this release).

**Comment by spiralw** [comment]
I can do that. I don't see an upgrading guide on your website, is there anything more that I need to do than installing the new version and restarting postgres?

**Comment by fabriziomello** [comment]
@spiralw here you can find this info: https://docs.timescale.com/timescaledb/latest/how-to-guides/upgrades/minor-upgrade/

**Comment by spiralw** [comment]
We upgraded to 2.9.1 and it seems to have fixed our issues. Thanks!

**Comment by spiralw** [comment]
Hi, unfortunately the issues came back :/ I had tried lowering the `shared_buffers` value since I had set it really high before opening this issue, and it started throwing "out of shared memory" errors again. I tried raising it back to 28GB but it is still throwing errors...

Is it normal for timescaledb to use a lot of RAM like this, when loading older chunks? If so, maybe timescaledb isn't great for our use case... please let me know.

**Comment by fabriziomello** [comment]
> Hi, unfortunately the issues came back :/ I had tried lowering the `shared_buffers` value since I had set it really high before opening this issue, and it started throwing "out of shared memory" errors again. I tried raising it back to 28GB but it is still throwing errors...
> 

:-(

> Is it normal for timescaledb to use a lot of RAM like this, when loading older chunks? If so, maybe timescaledb isn't great for our use case... please let me know.

No, it is not normal... but we need EXPLAIN output of the DELETE culprit query. Another question, are u sure the culprit are this DELETE query. There's no other process running at the same time (compression, refresh cagg, etc)???
