### ISSUE TITLE
[Bug]: ORDER/GROUP BY expression not found in targetlist with single table select

### ISSUE THREAD

**Issue by rodrigo-goncalves-ufsc** [timescale/timescaledb#6471]
### What type of bug is this?

Incorrect result, Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

While performing the following select (this is a Zabbix 6.4 install over a PG 16/tsdb 2.13):

```
SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=281535 AND h.clock>1703503754 GROUP BY h.itemid;
```

Over the following table:

```
                                                    Table "public.history"
 Column |       Type       | Collation | Nullable |        Default        | Storage | Compression | Stats target | Description
--------+------------------+-----------+----------+-----------------------+---------+-------------+--------------+-------------
 itemid | bigint           |           | not null |                       | plain   |             |              |
 clock  | integer          |           | not null | 0                     | plain   |             |              |
 value  | double precision |           | not null | '0'::double precision | plain   |             |              |
 ns     | integer          |           | not null | 0                     | plain   |             |              |
Indexes:
    "history_pkey" PRIMARY KEY, btree (itemid, clock, ns)
    "history_clock_idx1" btree (clock DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON history FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker()
Child tables: _timescaledb_internal._hyper_17_11662_chunk,
              _timescaledb_internal._hyper_17_11663_chunk,
              _timescaledb_internal._hyper_17_11672_chunk,
              _timescaledb_internal._hyper_17_11679_chunk,
              _timescaledb_internal._hyper_17_11684_chunk,
              _timescaledb_internal._hyper_17_11690_chunk,
              _timescaledb_internal._hyper_17_11694_chunk
Access method: heap
```

the following error is presented:

```
ERROR:  ORDER/GROUP BY expression not found in targetlist
```

### TimescaleDB version affected

2.13.0

### PostgreSQL version used

16.0

### What operating system did you use?

Ubuntu 22 - Docker image timescaledb:2.13.0-pg16

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Create the mentioned table, apply timescaledb over the table, insert some data and try to execute the mentioned group by select.

A select without the group by clause works flawlessly.
```

**Comment by rodrigo-goncalves-ufsc** [comment]
An aditionalnote: this seems to happen to any table. As an example:

```
zabbix=# select itemid, max(value_min) from trends where itemid=10 group by itemid;
ERROR:  ORDER/GROUP BY expression not found in targetlist
```

Structure:

```
                                                      Table "public.trends"
  Column   |       Type       | Collation | Nullable |        Default        | Storage | Compression | Stats target | Description
-----------+------------------+-----------+----------+-----------------------+---------+-------------+--------------+-------------
 itemid    | bigint           |           | not null |                       | plain   |             |              |
 clock     | integer          |           | not null | 0                     | plain   |             |              |
 num       | integer          |           | not null | 0                     | plain   |             |              |
 value_min | double precision |           | not null | '0'::double precision | plain   |             |              |
 value_avg | double precision |           | not null | '0'::double precision | plain   |             |              |
 value_max | double precision |           | not null | '0'::double precision | plain   |             |              |
Indexes:
    "trends_pkey1" PRIMARY KEY, btree (itemid, clock)
    "trends_clock_idx1" btree (clock DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON trends FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker()
Child tables: _timescaledb_internal._hyper_27_11677_chunk
Access method: heap
```

**Comment by antekresic** [comment]
This has been already fixed on main branch. Should be released in 2.13.1

https://github.com/timescale/timescaledb/pull/6377

**Comment by rodrigo-goncalves-ufsc** [comment]
Thanks for the prompt answer @antekresic ! We will wait for the release then.

**Comment by brianewell** [comment]
Still seeing this problem after having updated to v2.13.1.

**Comment by antekresic** [comment]
Can you try disabling this option and see if you get the same issue still?
`SET enable_presorted_aggregate to off;`

This will disable the PG16 optimization which was causing the problem I thought we fixed in 2.13.1

Thanks.

**Comment by rodrigo-goncalves-ufsc** [comment]
Hi, I've tried using the `SET enable_presorted_aggregate to off;` but the problem persists:

```
zabbix=#  SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=1049674 AND h.clock>1704884017 GROUP BY h.itemid;
ERROR:  ORDER/GROUP BY expression not found in targetlist
zabbix=# SET enable_presorted_aggregate to off;
SET
zabbix=#  SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=1049674 AND h.clock>1704884017 GROUP BY h.itemid;
ERROR:  ORDER/GROUP BY expression not found in targetlist
zabbix=#
```

**Comment by antekresic** [comment]
Hi again.

Would you mind doing one more thing? Try this setting and if it works capture the explain plan of the query.

```SET timescaledb.enable_chunkwise_aggregation to false```

Thanks again, this should help us get to the bottom of the issue.

**Comment by rodrigo-goncalves-ufsc** [comment]
Hi,

here's the output - setting the mentioned config to false allows the SQL to run:

```
zabbix=# SET timescaledb.enable_chunkwise_aggregation to false;
SET
zabbix=# SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=1049674 AND h.clock>1704884017 GROUP BY h.itemid;
 itemid  |   clock
---------+------------
 1049674 | 1704971693
(1 row)

zabbix=# explain SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=1049674 AND h.clock>1704884017 GROUP BY h.itemid;
                                                          QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=0.57..45.58 rows=1 width=12)
   ->  Append  (cost=0.57..44.63 rows=376 width=12)
         ->  Index Only Scan using "11782_209_history_pkey" on _hyper_17_11782_chunk h_1  (cost=0.57..11.27 rows=205 width=12)
               Index Cond: ((itemid = 1049674) AND (clock > 1704884017))
         ->  Index Only Scan using "11791_216_history_pkey" on _hyper_17_11791_chunk h_2  (cost=0.56..31.48 rows=171 width=12)
               Index Cond: ((itemid = 1049674) AND (clock > 1704884017))
(6 rows)
```

Trying to explain the query without setting the mentioned flag returns the same error:

```
zabbix=# SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=1049674 AND h.clock>1704884017 GROUP BY h.itemid;
ERROR:  ORDER/GROUP BY expression not found in targetlist
zabbix=# explain SELECT h.itemid,MAX(h.clock) AS clock FROM history h WHERE h.itemid=1049674 AND h.clock>1704884017 GROUP BY h.itemid;
ERROR:  ORDER/GROUP BY expression not found in targetlist
```

**Comment by rodrigo-goncalves-ufsc** [comment]
Let's wait for the feedback from @brianewell then - it is not too much trouble to upgrade since it is a minor version and our environment is based on docker over a VM (thus we can make snapshots and rollback in worst scenario).

**Comment by fabriziomello** [comment]
@rodrigo-goncalves-ufsc @brianewell hey folks, any news here?

**Comment by rodrigo-goncalves-ufsc** [comment]
Dear @fabriziomello just upgraded our instance today and can confirm that the problem is solved with this release!

**Comment by brianewell** [comment]
Sorry I've not had the availability to monitor github. My case was somewhat different in that we were experiencing this after grouping by columns from a joined metadata table. We ended up rewriting the join a bit to solve the issue.

**Comment by fabriziomello** [comment]
Thanks folks. Closing!
